<?php

namespace Modules\Flight\Controllers;

use App\Http\Controllers\Controller;
use Modules\Flight\Models\Flight;
use Illuminate\Http\Request;
use Modules\Flight\Models\FlightCategory;
use Modules\Location\Models\Location;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use DB;

class FlightController extends Controller
{
    protected $flightClass;
    protected $locationClass;
    protected $flightCategoryClass;
    protected $attributesClass;

    public function __construct()
    {
        $this->flightClass = Flight::class;
        $this->locationClass = Location::class;
        $this->flightCategoryClass = FlightCategory::class;
        $this->attributesClass = Attributes::class;
    }
    public function callAction($method, $parameters)
    {

        if (setting_item('flight_disable')) {
            die("123");
            return redirect('/');
        }


        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        die();
        $is_ajax = $request->query('_ajax');
        $list = call_user_func([$this->flightClass, 'search'], $request);
        $markers = [];
        if (!empty($list)) {
            foreach ($list as $row) {
                $markers[] = [
                    "id" => $row->id,
                    "title" => $row->title,
                    "lat" => (float) $row->map_lat,
                    "lng" => (float) $row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Flight::frontend.layouts.search.loop-gird', ['row' => $row, 'disable_lazyload' => 1, 'wrap_class' => 'infobox-item'])->render(),
                    'marker' => url('images/icons/png/pin.png'),
                ];
            }
        }
        $limit_location = 15;
        if (empty(setting_item("flight_location_search_style")) or setting_item("flight_location_search_style") == "normal") {
            $limit_location = 1000;
        }
        $data = [
            'rows' => $list,
            'flight_category' => $this->flightCategoryClass::where('status', 'publish')->with(['translations'])->get()->toTree(),
            'flight_location' => $this->locationClass::where('status', 'publish')->with(['translations'])->limit($limit_location)->get()->toTree(),
            'flight_min_max_price' => $this->flightClass::getMinMaxPrice(),
            'markers' => $markers,
            "blank" => 1,
            "seo_meta" => $this->flightClass::getSeoMetaForPageList()
        ];
        $layout = setting_item("flight_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        if ($is_ajax) {
            return $this->sendSuccess([
                'html' => view('Flight::frontend.layouts.search-map.list-item', $data)->render(),
                "markers" => $data['markers']
            ]);
        }
        $data['attributes'] = $this->attributesClass::where('service', 'flight')->with(['terms', 'translations'])->get();
        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Flight::frontend.search-map', $data);
        }
        return view('Flight::frontend.search', $data);
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->flightClass::where('slug', $slug)->with(['location', 'translations', 'hasWishList'])->first();
        if (empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }
        $translation = $row->translateOrOrigin(app()->getLocale());
        $flight_related = [];
        $location_id = $row->location_id;
        if (!empty($location_id)) {
            $flight_related = $this->flightClass::where('location_id', $location_id)->where("status", "publish")->take(4)->whereNotIn('id', [$row->id])->with(['location', 'translations', 'hasWishList'])->get();
        }
        $review_list = Review::where('object_id', $row->id)
            ->where('object_model', 'flight')
            ->where("status", "approved")
            ->orderBy("id", "desc")
            ->with('author')
            ->paginate(setting_item('flight_review_number_per_page', 5));
        $data = [
            'row' => $row,
            'translation' => $translation,
            'flight_related' => $flight_related,
            'booking_data' => $row->getBookingData(),
            'review_list' => $review_list,
            'seo_meta' => $row->getSeoMetaWithTranslation(app()->getLocale(), $translation),
            'body_class' => 'is_single'
        ];
        $this->setActiveMenu($row);
        return view('Flight::frontend.detail', $data);
    }
}
