<?php

namespace Modules\Flight\Controllers;

use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Flight\Models\Flight;
use Modules\Flight\Models\FlightCategory;
use Modules\Flight\Models\FlightTranslation;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Flight\Models\FlightTerm;
use Modules\Booking\Models\Booking;

class ManageFlightController extends FrontendController
{
    protected $flightClass;
    protected $flightTranslationClass;
    protected $flightCategoryClass;
    protected $flightTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;

    public function __construct()
    {
        $this->flightClass = Flight::class;
        $this->flightTranslationClass = FlightTranslation::class;
        $this->flightCategoryClass = FlightCategory::class;
        $this->flightTermClass = FlightTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;
        parent::__construct();
    }

    public function callAction($method, $parameters)
    {
        if (setting_item('flight_disable')) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageFlight(Request $request)
    {
        // $this->checkPermission('flight_view');
        $user_id = Auth::id();
        $list_flight = $this->flightClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_flight->paginate(5),
            'breadcrumbs' => [
                [
                    'name' => __('Manage Flights'),
                    'url'  => route('flight.vendor.index'),
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Manage Flights"),
        ];
        return view('FLight::frontend.manageFlight.index', $data);
    }

    public function createFlight(Request $request)
    {
        $this->checkPermission('flight_create');
        $row = new $this->flightClass();
        $data = [
            'row'           => $row,
            'translation'   => new $this->flightTranslationClass(),
            'flight_category' => $this->flightCategoryClass::get()->toTree(),
            'flight_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'flight')->get(),
            'breadcrumbs'   => [
                [
                    'name' => __('Manage Flights'),
                    'url'  => route('flight.vendor.index'),
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'    => __("Create Flights"),
        ];
        return view('Flight::frontend.manageFlight.detail', $data);
    }

    public function editFlight(Request $request, $id)
    {
        $this->checkPermission('flighti_update');
        $user_id = Auth::id();
        $row = $this->flightClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('flight.vendor.index'))->with('warning', __('Flight not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'            => $row,
            'flight_category'  => $this->flightCategoryClass::where("status", "publish")->get()->toTree(),
            'flight_location'  => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'     => $this->attributesClass::where('service', 'flight')->get(),
            "selected_terms" => $row->flight_term->pluck('term_id'),
            'breadcrumbs'    => [
                [
                    'name' => __('Manage Flights'),
                    'url'  => route('flight.vendor.index'),
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Edit Flights"),
        ];
        return view('Flight::frontend.manageFlight.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if ($id > 0) {
            $this->checkPermission('flight_update');
            $row = $this->flightClass::find($id);
            if (empty($row)) {
                return redirect(route('flight.vendor.edit', ['id' => $row->id]));
            }
            if ($row->create_user != Auth::id() and !$this->hasPermission('flight_manage_others')) {
                return redirect(route('flight.vendor.edit', ['id' => $row->id]));
            }
        } else {
            $this->checkPermission('flight_create');
            $row = new $this->flightClass();
            $row->status = "publish";
            if (setting_item("flight_vendor_create_service_must_approved_by_admin", 0)) {
                $row->status = "pending";
            }
        }
        $row->fillByAttr([
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'short_desc',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'gallery',
            'video',
            'default_state',
            'price',
            'sale_price',
            'duration',
            'max_people',
            'min_people',
            'faqs',
            'include',
            'exclude',
            'itinerary',
        ], $request->input());
        $row->ical_import_url = $request->ical_import_url;
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
                $row->saveMeta($request);
            }
            if ($id > 0) {
                return back()->with('success', __('Flight updated'));
            } else {
                return redirect(route('flight.vendor.edit', ['id' => $row->id]))->with('success', __('Flight created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->flightTermClass::where('flight_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->flightTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'flight_id' => $row->id
                ]);
            }
            $this->flightTermClass::where('flight_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function deleteFlight($id)
    {
        $this->checkPermission('flight_delete');
        $user_id = Auth::id();
        $query = $this->flightClass::where("create_user", $user_id)->where("id", $id)->first();
        if (!empty($query)) {
            $query->delete();
        }
        return redirect(route('flight.vendor.index'))->with('success', __('Delete flight success!'));
    }

    public function bulkEditFlight($id, Request $request)
    {
        $this->checkPermission('flight_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->flightClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if (empty($query)) {
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action) {
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReport(Request $request)
    {
        $data = [
            'bookings'    => $this->bookingClass::getBookingHistory($request->input('status'), false, Auth::id(), 'flight'),
            'statues'     => config('booking.statuses'),
            'breadcrumbs' => [
                [
                    'name' => __('Manage Flights'),
                    'url'  => route('flight.vendor.index'),
                ],
                [
                    'name'  => __('Booking Report'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Booking Report"),
        ];
        return view('Flight::frontend.manageFlight.bookingReport', $data);
    }

    public function bookingReportBulkEdit($booking_id, Request $request)
    {
        $status = $request->input('status');
        if (!empty(setting_item("flight_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if (!empty($item)) {
                $item->status = $status;
                $item->save();
                $item->sendStatusUpdatedEmails();
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }

    public function cloneFlight(Request $request, $id)
    {
        $this->checkPermission('flight_update');
        $user_id = Auth::id();
        $row = $this->flightClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('flight.vendor.index'))->with('warning', __('Flight not found!'));
        };
        try {
            $clone = $row->replicate();
            $clone->status = 'draft';
            $clone->push();
            if (!empty($row->flight_term)) {
                foreach ($row->flight_term as $term) {
                    $e = $term->replicate();
                    if ($e->push()) {
                        $clone->flight_term()->save($e);
                    }
                }
            }
            if (!empty($row->meta)) {
                $e = $row->meta->replicate();
                if ($e->push()) {
                    $clone->meta()->save($e);
                }
            }
            if (!empty($row->translations)) {
                foreach ($row->translations as $translation) {
                    $e = $translation->replicate();
                    $e->origin_id = $clone->id;
                    if ($e->push()) {
                        $clone->translations()->save($e);
                    }
                }
            }
            return redirect()->back()->with('success', __('Flight clone was successful'));
        } catch (\Exception $exception) {
            $clone->delete();
            return redirect()->back()->with('warning', __($exception->getMessage()));
        }
    }
}
